export const STOP_MAX_DURATION_HOURS = 24

export const STOP_MAX_DURATION_MS = STOP_MAX_DURATION_HOURS * 60 * 60 * 1000

export const STOP_TIME_STEP_MINUTES = 15

export const STOP_TIME_STEP_SECONDS = STOP_TIME_STEP_MINUTES * 60

export const MENU_ITEMS_GET_DELAY_MS = 500

export const MENU_ITEM_MUTATION_DELAY_MS = 600

export const MENU_ITEM_MUTATION_FAILURE_RATE = 0.2
